#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
import re

# Translation mapping for common terms
translations = {
    # Core terms
    "域名": "area",
    "顶点": "vertex",
    "顶级域名": "level 1 area",
    "一级域名": "level 1 area",
    "二级域名": "level 2 area",
    "三级域名": "level 3 area",
    "次级域名": "sub-area",
    "上级域名": "parent area",
    "联合域名": "surface name",
    "表面域名": "surface name",
    "维度": "dimension",
    "高度": "altitude",
    "坐标": "coordinate",
    "边界": "boundary",
    "创建者": "creator",
    "签名": "signature",
    "等级": "level",
    "颜色": "color",
    "记录": "record",
    "提交": "submit",
    "取消": "cancel",
    "确认": "confirm",
    "删除": "delete",
    "扩展": "expand",
    "收缩": "shrink",
    "分割": "divide",
    "重命名": "rename",
    "修改": "modify",
    "保存": "save",
    "加载": "load",
    "重新加载": "reload",
    "字幕": "subtitle",
    "样式": "style",
    "大小": "size",
    "渲染": "render",
    "检测": "detection",
    "频率": "frequency",
    "调试": "debug",
    "权限": "permission",
    "管理员": "administrator",
    "玩家": "player",
    "服务端": "server",
    "客户端": "client",
    "世界": "world",
    "文件夹": "folder",
    "配置": "config",
    "数据": "data",
    "错误": "error",
    "失败": "failed",
    "成功": "success",
    "完成": "complete",
    "开始": "start",
    "继续": "continue",
    "结束": "finish",
    "启用": "enabled",
    "禁用": "disabled",
    "有效": "valid",
    "无效": "invalid",
    "范围": "range",
    "最大": "max",
    "最小": "min",
    "最高": "highest",
    "最低": "lowest",
    "当前": "current",
    "新": "new",
    "旧": "old",
    "原": "original",
    "默认": "default",
    "自定义": "custom",
    "自动": "auto",
    "智能": "smart",
    "交互式": "interactive",
    "可视化": "visualization",
    "列表": "list",
    "选择": "select",
    "输入": "input",
    "点击": "click",
    "按键": "key",
    "按钮": "button",
    "提示": "hint",
    "警告": "warning",
    "注意": "note",
    "信息": "info",
    "消息": "message",
    "请求": "request",
    "响应": "response",
    "处理": "process",
    "发送": "send",
    "接收": "receive",
    "更新": "update",
    "设置": "set",
    "获取": "get",
    "查找": "find",
    "搜索": "search",
    "检查": "check",
    "验证": "validate",
    "计算": "calculate",
    "显示": "display",
    "隐藏": "hide",
    "进入": "enter",
    "离开": "leave",
    "切换": "switch",
    "变化": "change",
    "包含": "contain",
    "超出": "exceed",
    "不足": "insufficient",
    "至少": "at least",
    "最多": "at most",
    "所有": "all",
    "任意": "any",
    "无": "none",
    "空": "empty",
    "未知": "unknown",
    "未命名": "unnamed",
    "未找到": "not found",
    "不存在": "does not exist",
    "已存在": "already exists",
    "重复": "duplicate",
    "不能": "cannot",
    "必须": "must",
    "需要": "need",
    "要求": "require",
    "允许": "allow",
    "禁止": "prohibit",
    "可以": "can",
    "应该": "should",
    "将": "will",
    "已": "has",
    "正在": "is",
    "或": "or",
    "和": "and",
    "的": "",
    "了": "",
    "在": "in",
    "为": "for",
    "从": "from",
    "到": "to",
    "与": "with",
    "对": "to",
    "于": "at",
    "由": "by",
    "是": "is",
    "否": "no",
    "是": "yes",
}

def translate_text(text):
    """Translate Chinese text to English"""
    if not text or not isinstance(text, str):
        return text

    # Preserve Minecraft color codes
    color_pattern = r'§[0-9a-fk-or]'
    colors = re.findall(color_pattern, text)

    # Preserve placeholders
    placeholder_pattern = r'(\{[0-9]+\}|%s|%d|%.1f|\\n|\\\\)'
    placeholders = re.findall(placeholder_pattern, text)

    result = text

    # Simple word-by-word translation (this is a basic approach)
    # For production, you'd want to use a proper translation API

    # Common phrases first
    phrase_map = {
        "区域提示": "Areas Hint",
        "域名数据": "area data",
        "顶点坐标": "vertex coordinates",
        "高度范围": "altitude range",
        "上级域名": "parent area",
        "联合域名": "surface name",
        "创建者": "creator",
        "等级": "level",
        "颜色": "color",
        "维度": "dimension",
        "世界": "world",
        "服务端": "server",
        "客户端": "client",
        "玩家": "player",
        "管理员": "administrator",
        "权限": "permission",
        "配置": "configuration",
        "文件": "file",
        "文件夹": "folder",
        "数据": "data",
        "错误": "error",
        "失败": "failed",
        "成功": "success",
        "完成": "completed",
        "开始": "start",
        "继续": "continue",
        "取消": "cancel",
        "确认": "confirm",
        "提交": "submit",
        "保存": "save",
        "删除": "delete",
        "修改": "modify",
        "重命名": "rename",
        "扩展": "expand",
        "收缩": "shrink",
        "分割": "divide",
        "记录": "record",
        "选择": "select",
        "输入": "enter",
        "点击": "click",
        "按键": "key",
        "按钮": "button",
        "字幕": "subtitle",
        "样式": "style",
        "大小": "size",
        "渲染": "render",
        "检测": "detection",
        "频率": "frequency",
        "调试": "debug",
        "启用": "enabled",
        "禁用": "disabled",
        "有效": "valid",
        "无效": "invalid",
        "当前": "current",
        "新": "new",
        "旧": "old",
        "原": "original",
        "默认": "default",
        "自定义": "custom",
        "自动": "auto",
        "智能": "smart",
        "交互式": "interactive",
        "可视化": "visualization",
        "列表": "list",
        "提示": "hint",
        "警告": "warning",
        "注意": "note",
        "信息": "info",
        "消息": "message",
        "请求": "request",
        "响应": "response",
        "处理": "process",
        "发送": "send",
        "接收": "receive",
        "更新": "update",
        "设置": "set",
        "获取": "get",
        "查找": "find",
        "检查": "check",
        "验证": "validate",
        "计算": "calculate",
        "显示": "display",
        "进入": "enter",
        "离开": "leave",
        "切换": "switch",
        "包含": "contains",
        "超出": "exceeds",
        "不足": "insufficient",
        "至少": "at least",
        "所有": "all",
        "任意": "any",
        "无": "none",
        "空": "empty",
        "未知": "unknown",
        "未命名": "unnamed",
        "未找到": "not found",
        "不存在": "does not exist",
        "已存在": "already exists",
        "重复": "duplicate",
        "不能": "cannot",
        "必须": "must",
        "需要": "need",
        "允许": "allow",
        "可以": "can",
        "应该": "should",
        "将": "will",
        "正在": "is",
        "或": "or",
        "和": "and",
        "在": "in",
        "为": "for",
        "从": "from",
        "到": "to",
        "与": "with",
        "是": "yes",
        "否": "no",
        "您": "you",
        "你": "you",
        "我": "I",
        "它": "it",
        "这": "this",
        "那": "that",
        "个": "",
        "的": "",
        "了": "",
        "吗": "?",
        "呢": "?",
        "啊": "",
        "呀": "",
        "哦": "",
        "嗯": "",
    }

    for cn, en in phrase_map.items():
        result = result.replace(cn, en)

    return result

# Read the Chinese file
with open('zh_cn.json', 'r', encoding='utf-8') as f:
    zh_data = json.load(f, object_pairs_hook=dict)

# Create English translation
en_data = {}
for key, value in zh_data.items():
    if key == "language.name":
        en_data[key] = "English"
    elif key == "language.region":
        en_data[key] = "United States"
    elif key == "language.code":
        en_data[key] = "en_us"
    else:
        en_data[key] = translate_text(value)

# Write the English file
with open('en_us.json', 'w', encoding='utf-8') as f:
    json.dump(en_data, f, ensure_ascii=False, indent=2)

print("Translation completed! File saved as en_us.json")
