#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""将 zh_cn.json 自动转换为 LOLCAT en_pt.json"""
import json, re, random

random.seed(42)

src = r"src/main/resources/assets/areas-hint/lang/zh_cn.json"
dst = r"src/main/resources/assets/areas-hint/lang/en_pt.json"

with open(src, "r", encoding="utf-8") as f:
    data = json.load(f)

# 特殊键直接覆盖
OVERRIDES = {
    "language.code": "en_pt",
    "language.name": "LOLCAT",
    "language.region": "Internetz",
}

# 中文→英文 短语映射（按长度降序排列，优先匹配长短语）
PHRASE_MAP = [
    # --- 长短语优先 ---
    ("区域提示模组客户端初始化完成", "area hint mod client init dun"),
    ("区域提示模组服务端初始化完成", "area hint mod server init dun"),
    ("区域提示模组客户端初始化中", "area hint mod client initializin"),
    ("区域提示模组服务端初始化中", "area hint mod server initializin"),
    ("重新加载区域提示模组配置和区域数据", "reloadin area hint mod config an area data"),
    ("区域提示模组: 服务器已停止", "area hint mod: server stoppd"),
    ("区域提示模组: 服务器启动中", "area hint mod: server startin"),
    ("区域提示调试模式", "area hint debug mode"),
    ("已启用区域提示调试模式，您将收到实时调试信息", "area hint debug mode ON, u will get realtime debug info"),
    ("已禁用区域提示调试模式", "area hint debug mode OFF"),
    ("交互式域名添加", "interactive area naem addin"),
    ("交互式域名重命名", "interactive area naem renamin"),
    ("交互式域名重命名流程", "interactive area naem rename process"),
    ("交互式删除域名", "interactive area naem deletin"),
    ("交互式设置字幕样式", "interactive subtitle style settin"),
    ("交互式设置字幕大小", "interactive subtitle size settin"),
    ("交互式扩展域名区域", "interactive expand area naem"),
    ("交互式收缩域名区域", "interactive shrink area naem"),
    ("交互式分割域名区域", "interactive divide area naem"),
    ("交互式高度设置流程", "interactive altitude settin process"),
    ("字幕渲染方式信息已发送到客户端", "subtitle render info sent 2 client"),
    ("字幕渲染方式已设置为", "subtitle render set 2"),
    ("检测频率信息已发送到客户端", "detecshun frequency info sent 2 client"),
    ("检测频率已设置为", "detecshun frequency set 2"),
    ("区域数据和维度域名配置已重新加载并发送给所有客户端", "area data an dimenshun config reloadd an sent 2 all clients"),
    ("已重新发送维度域名配置给所有客户端", "resent dimenshun config 2 all clients"),
    ("维度域名颜色已更新", "dimenshun area naem color updatd"),
    ("维度域名已更新", "dimenshun area naem updatd"),
    ("域名显示和检测功能已开启", "area naem display an detecshun iz ON"),
    ("域名将不再显示，但仍会接收服务器数据", "area naems wont show but still receivin server data"),
    ("模组已通过命令启用", "mod enabled via command"),
    ("模组已通过命令禁用", "mod disabled via command"),
    ("此指令只能由玩家执行", "dis command can only be run by a player"),
    ("此命令只能由玩家执行", "dis command can only be run by a player"),
    ("该命令只能由玩家执行", "dis command can only be run by a player"),
    ("输入格式错误，请输入有效的数字", "input format error, PLZ enter valid numbr"),
    ("无效的JSON数据，请检查格式", "invalid JSON data, check teh format PLZ"),
    ("命令执行失败", "command faild"),
    ("执行命令时出错", "error executin command"),
    ("执行命令时发生错误，请稍后重试", "error executin command, try again l8r PLZ"),
    ("有效选项: cpu, opengl, vulkan", "valid opshuns: cpu, opengl, vulkan"),
    ("无效的渲染方式", "invalid render method"),
    ("设置或显示检测频率", "set or show detecshun frequency"),
    ("设置或显示字幕渲染方式", "set or show subtitle render"),
    ("修改指定域名的颜色", "modify area naem color"),
    ("向域名添加顶点", "add vertices 2 area naem"),
    ("从域名删除顶点", "delete vertices from area naem"),
    ("切换域名边界可视化显示", "toggle area naem boundary vizualizashun"),
    ("交互式选择模组语言", "interactive language selecshun"),
    ("更改记录域名顶点的按键", "change area naem vertex record key"),
    ("查看联合域名信息", "view surface naem info"),
    ("管理维度域名", "manage dimenshun area naems"),
    ("修改维度域名颜色", "modify dimenshun area naem color"),
    ("列出当前维度可修改高度的域名", "list area naems wif modifiable altitude in dis dimenshun"),
    ("为当前维度设置首次命名", "set first naem 4 current dimenshun"),
    ("跳过维度首次命名（使用默认名称）", "skip dimenshun first namin (use default naem)"),
    ("切换调试模式", "toggle debug mode"),
    ("重新加载配置和域名文件", "reload config an area naem files"),
    ("显示此帮助", "show dis halp"),
    ("添加新的域名 (已弃用)", "add new area naem (deprecated)"),
    ("启动交互式域名添加", "start interactive area naem addin"),
    ("设置服务端日志语言 (仅控制台)", "set server log language (console only)"),
    ("服务端语言已设置为", "server language set 2"),
    # --- 域名/区域相关 ---
    ("联合域名", "surface naem"),
    ("维度域名", "dimenshun area naem"),
    ("顶级域名", "level 1 area"),
    ("一级域名", "level 1 area"),
    ("二级域名", "level 2 area"),
    ("三级域名", "level 3 area"),
    ("次级域名", "sub-level area"),
    ("上级域名", "parent area naem"),
    ("域名等级", "area naem level"),
    ("域名名称", "area naem naem"),
    ("域名颜色", "area naem color"),
    ("域名信息", "area naem info"),
    ("域名数据", "area naem data"),
    ("域名边界", "area naem boundary"),
    ("域名高度", "area naem altitude"),
    ("域名重命名", "area naem rename"),
    ("域名分割", "area naem divide"),
    ("域名扩展", "area naem expand"),
    ("域名收缩", "area naem shrink"),
    ("域名文件", "area naem file"),
    ("域名列表", "area naem list"),
    ("域名验证", "area naem validashun"),
    ("域名", "area naem"),
    # --- 维度 ---
    ("维度文件名", "dimenshun file naem"),
    ("维度文件", "dimenshun file"),
    ("维度名称", "dimenshun naem"),
    ("维度颜色", "dimenshun color"),
    ("维度", "dimenshun"),
    # --- 顶点 ---
    ("一级顶点", "level 1 vertices"),
    ("二级顶点", "level 2 vertices"),
    ("顶点坐标", "vertex coordinates"),
    ("顶点数量", "vertex count"),
    ("顶点更新", "vertex update"),
    ("顶点删除", "vertex delete"),
    ("顶点", "vertex"),
    # --- 高度 ---
    ("高度范围", "altitude range"),
    ("高度设置", "altitude settin"),
    ("高度限制", "altitude limit"),
    ("高度值", "altitude value"),
    ("高度数据", "altitude data"),
    ("最高高度", "max altitude"),
    ("最低高度", "min altitude"),
    ("高度", "altitude"),
    # --- 颜色 ---
    ("自定义颜色", "custom color"),
    ("十六进制", "hex"),
    ("天蓝色", "sky bloo"),
    ("湖蓝色", "lake bloo"),
    ("深灰色", "dark gray"),
    ("深红色", "dark red"),
    ("深绿色", "dark green"),
    ("深蓝色", "dark bloo"),
    ("浅绿色", "lite green"),
    ("浅蓝色", "lite bloo"),
    ("浅紫色", "lite purpul"),
    ("粉红色", "pink"),
    ("橙色", "orang"),
    ("灰色", "gray"),
    ("白色", "wite"),
    ("红色", "red"),
    ("绿色", "green"),
    ("蓝色", "bloo"),
    ("黄色", "yellow"),
    ("黑色", "blak"),
    ("紫色", "purpul"),
    ("棕色", "brown"),
    ("颜色", "color"),
    # --- 字幕/渲染 ---
    ("字幕大小", "subtitle size"),
    ("字幕样式", "subtitle style"),
    ("字幕渲染方式", "subtitle render"),
    ("完整样式", "full style"),
    ("混合样式", "mixed style"),
    ("简洁样式", "simple style"),
    ("边界可视化", "boundary vizualizashun"),
    ("渲染方式", "render method"),
    ("渲染管理器", "render managr"),
    # --- 操作动词 ---
    ("已取消", "canceld"),
    ("已提交", "submittd"),
    ("已启动", "startd"),
    ("已保存", "savd"),
    ("已加载", "loadd"),
    ("已创建", "creatd"),
    ("已设置", "set"),
    ("已更新", "updatd"),
    ("已接收", "receivd"),
    ("已发送", "sent"),
    ("已记录", "recordd"),
    ("已选择", "selectd"),
    ("已重置", "reset"),
    ("已启用", "enabled"),
    ("已禁用", "disabled"),
    ("已存在", "already existz"),
    ("已弃用", "deprecated"),
    ("已使用", "usin"),
    ("已向", "sent 2"),
    ("已从", "from"),
    ("已连接", "connectd"),
    ("不存在", "no exist"),
    ("不能", "cant"),
    ("不足", "not enuf"),
    ("无法", "cant"),
    ("无效", "invalid"),
    ("无限制", "no limit"),
    ("未找到", "not found"),
    ("未知", "unknown"),
    ("失败", "faild"),
    ("成功", "success"),
    ("错误", "error"),
    ("警告", "warnin"),
    # --- 常用动词 ---
    ("请选择", "PLZ select"),
    ("请输入", "PLZ enter"),
    ("请确认", "PLZ confirm"),
    ("请确保", "PLZ make sure"),
    ("请在聊天框中输入", "PLZ type in chat"),
    ("请在聊天中发送消息即可", "just send a msg in chat"),
    ("请按下", "PLZ press"),
    ("请稍后重试", "try again l8r PLZ"),
    ("请检查", "PLZ check"),
    ("正在处理", "processin"),
    ("正在获取", "gettin"),
    ("正在发送", "sendin"),
    ("正在加载", "loadin"),
    ("发送到服务端", "sent 2 server"),
    ("发送到客户端", "sent 2 client"),
    ("发送给所有", "sent 2 all"),
    ("发送请求", "sendin request"),
    ("发送响应", "sendin response"),
    ("发送", "send"),
    ("接收到", "receivd"),
    ("接收", "receive"),
    ("处理请求", "processin request"),
    ("处理", "process"),
    ("保存文件", "save file"),
    ("保存配置", "save config"),
    ("保存", "save"),
    ("加载", "load"),
    ("删除", "delete"),
    ("添加", "add"),
    ("修改", "modify"),
    ("更改", "change"),
    ("更新", "update"),
    ("重命名", "rename"),
    ("重新加载", "reload"),
    ("重新发送", "resend"),
    ("重新", "re-"),
    ("取消", "cancel"),
    ("确认", "confirm"),
    ("提交", "submit"),
    ("选择", "select"),
    ("输入", "enter"),
    ("记录", "record"),
    ("创建", "create"),
    ("启动", "start"),
    ("开始", "start"),
    ("完成", "dun"),
    ("初始化", "init"),
    ("设置", "set"),
    ("切换", "toggle"),
    ("显示", "show"),
    ("查看", "view"),
    ("检测", "detect"),
    ("检查", "check"),
    ("管理", "manage"),
    ("扩展", "expand"),
    ("收缩", "shrink"),
    ("分割", "divide"),
    ("执行", "execute"),
    ("获取", "get"),
    ("读取", "read"),
    ("写入", "write"),
    ("解析", "parse"),
    ("广播", "broadcast"),
    ("配置", "config"),
    ("计算", "calculate"),
    ("验证", "validate"),
    ("排序", "sort"),
    ("筛选", "filter"),
    ("包含", "containz"),
    ("超出", "exceedz"),
    ("进入", "enterd"),
    ("离开", "left"),
    ("返回", "return"),
    ("使用", "usin"),
    ("生成", "generate"),
    ("清理", "cleanup"),
    ("强制", "force"),
    # --- 名词 ---
    ("创建者", "creator"),
    ("管理员", "admin"),
    ("玩家", "player"),
    ("服务器", "server"),
    ("服务端", "server"),
    ("客户端", "client"),
    ("世界", "world"),
    ("区域", "area"),
    ("坐标", "coordinates"),
    ("坐标点", "coordinate point"),
    ("位置", "posishun"),
    ("方向", "direcshun"),
    ("范围", "range"),
    ("等级", "level"),
    ("名称", "naem"),
    ("按钮", "button"),
    ("按键", "key"),
    ("界面", "UI"),
    ("流程", "process"),
    ("模式", "mode"),
    ("功能", "feachur"),
    ("模组", "mod"),
    ("指令", "command"),
    ("命令", "command"),
    ("权限", "permishun"),
    ("文件", "file"),
    ("文件夹", "folder"),
    ("路径", "path"),
    ("目录", "directory"),
    ("数据", "data"),
    ("信息", "info"),
    ("消息", "msg"),
    ("状态", "status"),
    ("结果", "result"),
    ("条件", "condishun"),
    ("选项", "opshun"),
    ("格式", "format"),
    ("内容", "content"),
    ("长度", "length"),
    ("大小", "size"),
    ("数量", "count"),
    ("总计", "total"),
    ("默认", "default"),
    ("当前", "current"),
    ("原始", "original"),
    ("新的", "new"),
    ("旧的", "old"),
    ("有效", "valid"),
    ("合理", "reasonable"),
    ("自定义", "custom"),
    ("交互式", "interactive"),
    ("可视化", "vizualizashun"),
    ("调试", "debug"),
    ("日志", "log"),
    ("频率", "frequency"),
    ("语言", "language"),
    # --- 补充缺失词汇 ---
    ("继续", "continue"),
    ("按", "press"),
    ("键", "key"),
    ("不限制", "no limit"),
    ("限制", "limit"),
    ("可修改", "modifiable"),
    ("可编辑", "editable"),
    ("可删除", "deletable"),
    ("可扩展", "expandable"),
    ("可收缩", "shrinkable"),
    ("可分割", "dividable"),
    ("暂无", "none yet"),
    ("仍会", "still"),
    ("仍然", "still"),
    ("仍", "still"),
    ("符合", "match"),
    ("预览", "preview"),
    ("字节", "bytes"),
    ("进行中", "in progress"),
    ("进行", "proceed"),
    ("存在", "exist"),
    ("循环引用", "circular ref"),
    ("引用", "ref"),
    ("对应", "correspond 2"),
    ("翻译", "translashun"),
    ("条", " "),
    ("闪烁", "blinky"),
    ("彩虹", "rainbow"),
    ("黑白", "blak an wite"),
    ("单字", "per-char"),
    ("整体", "whole"),
    ("效果", "effect"),
    ("样式", "style"),
    ("最终", "final"),
    ("最大", "max"),
    ("最小", "min"),
    ("线段", "line segment"),
    ("交叉", "intersecshun"),
    ("多边形", "polygon"),
    ("射线", "ray"),
    ("交点", "intersecshun point"),
    ("凸包", "convex hull"),
    ("角度", "angle"),
    ("反转", "reverse"),
    ("反向", "reverse"),
    ("临近点", "nearby point"),
    ("边界点", "boundary point"),
    ("中心点", "center point"),
    ("起始", "start"),
    ("结束", "end"),
    ("索引", "index"),
    ("序号", "index"),
    ("算法", "algorithm"),
    ("通过", "via"),
    ("指定", "specify"),
    ("正确", "correct"),
    ("相同", "same"),
    ("不同", "different"),
    ("相交", "intersect"),
    ("穿过", "pass thru"),
    ("恰好", "exactly"),
    ("自动", "auto"),
    ("手动", "manual"),
    ("依次", "one by one"),
    ("精确", "precise"),
    ("控制", "control"),
    ("生效", "active"),
    ("适用于", "iz 4"),
    ("跨越", "span"),
    ("层", "layer"),
    ("大型", "big"),
    ("基于", "based on"),
    ("智能", "smart"),
    ("留空", "leave empty"),
    ("则", "then"),
    ("例如", "e.g."),
    ("根据", "based on"),
    ("调整", "adjust"),
    ("商业区", "commercial zone"),
    ("住宅区", "residential zone"),
    ("工业区", "industrial zone"),
    ("超时", "timeout"),
    ("命名", "namin"),
    ("分钟", "min"),
    ("内未", "not within"),
    ("将", "will"),
    ("给", "2"),
    ("被", "by"),
    ("把", " "),
    ("让", "let"),
    ("跳过", "skip"),
    ("回车", "Enter"),
    ("空格", "Space"),
    ("退格", "Backspace"),
    ("上箭头", "Up Arrow"),
    ("下箭头", "Down Arrow"),
    ("左箭头", "Left Arrow"),
    ("右箭头", "Right Arrow"),
    # --- 连接词/助词（多字优先） ---
    ("没有", "no "),
    ("不是", "iz not "),
    ("不能再", "cant "),
    ("不能", "cant "),
    ("时发生", " "),
    ("时出错", " error"),
    ("可以", "can "),
    ("需要", "need "),
    ("至少", "at least "),
    ("只能", "can only "),
    ("必须", "must "),
    ("可能", "maybe "),
    ("如果", "if "),
    ("因为", "cuz "),
    ("但是", "but "),
    ("所有", "all "),
    ("每个", "each "),
    ("其他", "other "),
    ("以上", "an above"),
    ("以下", "an below"),
    ("之间", "between"),
    ("内部", "inside"),
    ("外部", "outside"),
    # --- 单字助词（最后） ---
    ("的", " "),
    ("了", " "),
    ("在", " in "),
    ("到", " 2 "),
    ("从", " from "),
    ("为", " 4 "),
    ("和", " an "),
    ("或", " or "),
    ("与", " an "),
    ("是", " iz "),
    ("有", " haz "),
    ("但", " but "),
    ("个", " "),
    ("中", " in "),
    ("后", " after "),
    ("前", " before "),
    ("上", " on "),
    ("下", " below "),
    ("新", " new "),
    ("旧", " old "),
    ("原", " original "),
    ("该", " dis "),
    ("此", " dis "),
    ("您", " u "),
    ("你", " u "),
    ("我", " I "),
    # --- 世界名 ---
    ("恶堕之域", "teh Nether"),
    ("终末之地", "teh End"),
    ("蛮荒大陆", "teh Overworld"),
    # --- 杂项 ---
    ("简体中文", "Simplified Chinese"),
    ("仅控制台", "console only"),
    ("管理员专用", "admin only"),
    ("不可逆", "cant be undun"),
    ("无法恢复", "cant be recoverd"),
    ("谨慎操作", "be careful"),
    ("点击", "click"),
    ("提示", "hint"),
    ("注意", "note"),
    ("用法", "usage"),
    ("帮助", "halp"),
    ("关闭", "OFF"),
    ("开启", "ON"),
    ("启用", "enabled"),
    ("禁用", "disabled"),
    ("是", "yes"),
    ("否", "no"),
]

# LOLCAT 尾巴
TAILS = ["", " MEOW", " kthx", " MEW", " lol", ""]

def translate_value(key, val):
    """翻译一个值为LOLCAT英语"""
    if key in OVERRIDES:
        return OVERRIDES[key]
    if not val or len(val.strip()) <= 1:
        return val

    # 保护 tokens
    tokens = {}
    token_id = 0
    def protect(m):
        nonlocal token_id
        tok = f"\x00T{token_id}\x00"
        tokens[tok] = m.group(0)
        token_id += 1
        return tok

    protected = re.sub(r'§[0-9a-fk-or]', protect, val)
    protected = re.sub(r'\{[0-9]*\}|%[sd]|%\.\d+[fd]', protect, protected)
    protected = re.sub(r'\\\\n|\\n', protect, protected)
    protected = re.sub(r'#[0-9A-Fa-f]{6}', protect, protected)

    # 应用短语映射，替换时在英文两侧加空格标记
    result = protected
    for cn, en in PHRASE_MAP:
        if cn in result:
            result = result.replace(cn, f" {en} ", 1)

    # 清理残留中文常见字符（标点等）
    result = result.replace("，", ", ").replace("。", ". ").replace("：", ": ")
    result = result.replace("！", "! ").replace("？", "? ").replace("；", "; ")
    result = result.replace("（", "(").replace("）", ")").replace("、", ", ")
    result = result.replace("《", "<").replace("》", ">")

    # 删除残留的单个中文字符（助词等）
    result = re.sub(r'[\u4e00-\u9fff]', '', result)

    # 还原tokens
    for tok, orig in tokens.items():
        result = result.replace(tok, orig)

    # 清理多余空格
    result = re.sub(r'  +', ' ', result).strip()
    # 恢复原始前导空格
    leading = len(val) - len(val.lstrip())
    if leading > 0:
        result = val[:leading] + result

    # 偶尔加LOLCAT尾巴
    stripped = result.rstrip()
    if (len(stripped) > 25
        and stripped[-1] not in ":,. {}()[]§\\'\""
        and not stripped.endswith("===")
        and not stripped.endswith("]")
        and random.random() < 0.12):
        result = stripped + random.choice([" MEOW", " kthx", " MEW"])

    return result

# 执行翻译
output = {}
for key, val in data.items():
    output[key] = translate_value(key, val)

with open(dst, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"LOLCAT translation done! {len(output)} entries -> {dst}")
